### ISSUE TITLE
full css path

### ISSUE THREAD

**Issue by norbi771** [flamencist/CssPath#1]
I am glad that you created that extension. 
I wish I could extract full css path, not only most relevant part. 
Firebug is doing that in the way I described. 

Let's imagine I am debugging complex html code and 

your solution:
"tbody#CouponListForm\3a datalist_data > tr.ui-widget-content.ui-datatable-odd.ui-datatable-selectable.ui-state-hover > td:nth-child(2)

firebug:
html body.ui-layout-container div#j_idt24.ui-layout-unit.ui-widget.ui-widget-content.ui-corner-all.ui-layout-center.ui-layout-pane.ui-layout-pane-center div.ui-layout-unit-content.ui-widget-content form#CouponListForm div#CouponListForm:j_idt25.ui-panel.ui-widget.ui-widget-content.ui-corner-all div#CouponListForm:j_idt25_content.ui-panel-content.ui-widget-content div#CouponListForm:datalist.ui-datatable.ui-widget.ui-datatable-scrollable div.ui-datatable-scrollable-body table tbody#CouponListForm:datalist_data.ui-datatable-data.ui-widget-content tr.ui-widget-content.ui-datatable-odd.ui-datatable-selectable td

Do you think it is possible?

Best regards
Norbert

**Comment by flamencist** [comment]
Yes, it is possible.
I added new property "path" for showing full path of web element.
It's available in next version v0.2
